### ISSUE TITLE
Static groups

### ISSUE THREAD

**Issue by ludw** [asheidan/DistSys-Project#12]
Förslag på implementation:
Låt folk joina gruppen tills alla är där, klicka på "freeze group" vilket kan vara en knapp längst ner i medlemslistan eller något. Ingen kan skriva förrens gruppen är låst. När den är låst kan ingen joina. Lämnar någon går det inte att skriva förrens de är åter.

**Comment by asheidan** [comment]
Enligt specen skulle gruppen fortfarande fungera om någon lämnade gruppen men man skulle inte kunna joina igen. Vad tror du om att bara ignorera join-requests när man har frusit gruppen?

**Comment by asheidan** [comment]
Mastodontcommit. Static groups. Closed by 111136d6e6e53d9f7ada690a3281ff59281fa503.
