### ISSUE TITLE
Sometimes causal + reliable give strange results

### ISSUE THREAD

**Issue by ludw** [asheidan/DistSys-Project#13]
The message is duplicated on the sender part but not on the receivers. Messages might also appear both at the top and the bottom of the chat window at the same time. Really strange stuff. 
Only happens sometimes.

**Comment by ludw** [comment]
Fixed. Was due to bad hash from message. Using string-form of vector clock might give
(a=1, b=2) or (b=2, a=1) which isn't equal. Uses hashCode() on clocks in vectorclock instead.

**Comment by asheidan** [comment]
Closed by 779a38ea79aba745d9247ab44cedfecfa792f0bd
