### ISSUE TITLE
Join bug with reliable multicast

### ISSUE THREAD

**Issue by ludw** [asheidan/DistSys-Project#6]
Nisse
Nusse
Arne
Nisse
Nusse
Arne
Arne
Arne

**Comment by asheidan** [comment]
The bug was caused by RMC not remembering sent messages as well as received.
GOTMEMBER was passed around to all members and not only the ones who was in the group before the join.

**Comment by asheidan** [comment]
Closed by 7e05a6b8db99a973d3e70f02e3473f0ecc0121e2
